# Introduction

\minitoc

## Disrupting technologies

The title of this thesis contains an ambiguous phrase: "disrupting technologies". Does the gerund mean to say technologies are causing a disruption or technologies are being disrupted?[^1.1] The idea that technologies are disrupting the economic and social status quo has a time-honoured history from the days of the Industrial Revolution to the present. The *Communist Manifesto* sang paeans to the bourgeoisie's revolutionising of the means of production, dislodging old industries and old class hierarchies, creating a universal condition of capitalist relations, proletarianisation, and "interdependence of all nations", thus paving the way to a communist society [@marx_manifesto_1848, 488]. Evolutionary theories, rooted in the Gilded Age of the Second Industrial Revolution, contended more modestly that technologies transform institutions and, in turn, transform societies [@veblen_theory_1899]. Or that innovations drive business cycles to destroy stagnant capital, unleashing new productive forces [@schumpeter_capitalism_1942]. From there, the idea of technological disruption developed into a watchword of contemporary business theory, most notably enshrined in Clayton Christensen's concept of "disruptive innovation" [-@christensen_innovators_1997], foregrounding how emerging, smaller firms can use innovative business models and technologies to create new markets, push out the oligopolistic incumbents protecting their sunk investments, and thus disrupt the economic structure and the larger social order. Over the last couple of decades, as microcomputing and digitisation have unsettled traditional industries, technological disruption has thus become imperative for businesses and social institutions alike, leading the barons of industry such as Mark Zuckerberg to profess that they want "to move fast and break things" — openly courting a "destruction rhetoric" [@zuboff_age_2019, 50-51].[^1.2] As a consequence, expectations that technologies can disrupt the impasses of status quo, that they are the most expedient way to tackle the hardest societal challenges, have thus come to dominate the contemporary social imaginary.

Environmental policies are no exception. The cornerstone tenet of the UN Framework Convention on Climate Change (UNFCC), ensconced in the Kyoto Protocol, is that climate protection should be achieved through ecological modernisation [@backstrand_climate_2016]. Ecological modernisation assumes that, by using technologies and markets to replace the old fossil-fuelled technological base, economic growth can be harmonised with environmental sustainability. There is some merit to these expectations: pollution does happen through technologies. They are at least its material cause. However, many researchers indicate that — given the state of green technologies development, the historical and present technological replacement rates, and the current investments into these technologies [@loftus_critical_2015; @anderson_trouble_2016; @allwood_technology_2021; @hansen_november_2021] — such expectations underestimate the scale and the temporality of the challenge of limiting the global warming to the aspired 1.5 or 2°C above the pre-industrial levels.

These expectations thus might be unrealistic. The attained scale of the existing polluting technological infrastructures in energy generation, manufacturing, industrial agriculture, heating and cooling, which has been likened to a geological sphere — a technosphere [@haff_technology_2014], makes the rapid and disruptive replacement of fossil fuels much more challenging than were the changes in communication, coordination, and administration brought about by digital technologies. While significant advances have been made in energy generation, all other technological systems remain highly dependent on fossil fuels. Fossil fuels still account for around 85% of the world's primary energy demand [@ren21_five_2021]. Additionally, the temporal horizon for this colossal transition to a sustainable technological base is limited. As the IPCC warned in 2018, at the current rate of greenhouse gas emissions, by 2030 the world will have exhausted its carbon budget to remain within 50:50 chances of keeping the global warming down to 1.5°C [@ipcc_global_2018]. Contemporary industrial-capitalist metabolism, premised on the intensive extraction of matter and energy from nature, has been developed over centuries. Replacing it in a few short decades might not be achievable. Placing primacy on technologies in this rapid transition to sustainability might not yield timely results, implying that societies might need to consider other far-reaching transformations, including changes to their economic systems and their provisioning for social needs, to meet the goals of stabilising climate and other Earth's biophysical subsystems more easily. *Thus, to reverse the expectations implied in the title, is it not the technology-first strategies that might need to be disrupted?*[^1.3]

And indeed, both the Intergovernmental Panel on Climate Change (IPCC) and the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services (IPBES) have called for "transformative changes across economic, social, political and technological factors" [@ipbes_global_2019]. While scientists thus demand transformative changes across different societal (sub)systems, policymakers stick to the changes to technology and energy systems, avoiding direct interventions into wasteful and unsustainable patterns of production and provision sustained by these technological and energy systems. Partly because social or political changes are more difficult to negotiate and enact than technological changes, both nationally and, in particular, internationally. But partly also because technologies are central to economic growth, develop from the capitalist centre, and redistribute social and environmental wealth to the centre [@hornborg_global_2016]. Technologies might be a material cause of pollution, but its efficient and final causes are economic, social, and political.

Policymakers' technological bias is only reaffirmed in the political imaginary by notions such as Anthropocene. The Anthropocene instils the idea that human ingenuity has caused this predicament and now that ingenuity has to solve it: to transform from a reckless planetary polluter to a responsible planetary steward. As degrowth scholar Stefania Barca [-@barca_forces_2020] has forcefully argued, such reasoning is an ideational extension of the aspiration for human mastery over nature. It ignores that the Earth's systems' stability has rested on the contributions of relations other than those of capitalist production: socially and environmentally reproductive relations fostered by subsistence farmers, land protectors, care-labourers, other species, and ecosystems that pre-date technological revolutions. Packing together a sense of human hubris and a sense of an impending catastrophe, notions such as Antrhopocenes thus occlude and foreclose class and other social antagonisms that inhere in climate crisis [@swyngedouw_apocalypse_2013].

Facing these scalar, temporal, and ideational challenges, the centrality of markets and technologies in the transition to a purportedly sustainable future needs to be scrutinized and contested.

## Thesis at a glance

The primary objective of this thesis is to investigate the proposals of alternative environmental action contesting that centrality and thus filling the gap between what science demands and what policy delivers. This thesis looks to proposals that might counteract a potential failure of the market-driven technology-first strategies to prevent a runaway global warming, but also to proposals that democratically ground environmental action in the lived reality of communities in a highly unequal world. The closing time window makes it urgent and necessary that the proponents of these alternatives shift the dominant framing of effective climate action: from ecological modernisation, aimed at harmonising economic growth with environmental sustainability, to framings that prioritise social wellbeing within the limits of a stabilised planetary ecology. This thesis responds to the urgency and the necessity of that frameshift.

To pursue that objective, I focus on two framings, their two proponents, and their exemplary agency. I do so to reflect the fact that social metabolisms[^1.4] encompass both *the systems of production* and *the systems of provision for social needs* and that they vary immensely between the affluent countries of the capitalist centre and the capitalist (semi)periphery. For this purpose, in the context of the European post-socialist semiperiphery, I investigate the activities of the Institute for Political Ecology (IPE), a research and educational organisation developing proposals for degrowth. Degrowth environmentalism offers a framing in which the limiting of economic growth in affluent societies, when accompanied by a redistribution of existing social wealth and an economy designed to provide the wellbeing for all, would lower the demand for material extraction and energy generation. This would ease the technological challenge of rapid decarbonisation and allow non-affluent societies to pursue their own development paths. The perspective from a post-socialist semiperiphery contributes a sense that a social transition to sufficiency might be politically feasible under conditions of large-scale redistribution and distributive justice.

Conversely, in the context of the European capitalist centre, I investigate the activities of the UK's largest industrial labour organisation, Unite the Union (Unite), whose environmental activities are aimed at developing proposals along the lines of a just transition and green new deal. The idea of a green new deal offers a framing in which the greening of the economy is fundamentally tied to making increasingly unequal economies more equitable and welfare provisions more comprehensive. To facilitate that coupled social and industrial transformation, such proposals are frequently premised on nationalising key polluting sectors such as energy and transport and socialising key welfare sectors such as healthcare, education, and housing. The perspective from the capitalist centre and its industrial base contributes a more ambivalent sense of the uncertainties of future transitions and sustainability.

The selection of these two actors as case studies has been motivated, however, by a desire to complicate the binaries through which their approaches are typically contrasted: working-class vs social-metabolism-oriented environmentalism, capitalist centre vs (semi)periphery, production vs social reproduction.[^1.5] By providing a pluriperspectival account of these organisations' strategic-operational contexts, my research aspires toward an understanding of the prospects of these two environmental positions in the present political conjuncture.

The research for this thesis has unfolded in two phases. In the first phase, I sought to ground the empirical research in historical, strategic, and political-epistemic analyses of the constraining and enabling factors such alternative framings and their proponents face. My inquiry drew on various disciplines and approaches — including ecological Marxism, environmental history, science and technology studies, post-normal science, strategic-relational approach, and institutional logics theory — in order to adequately conceptualise the current terrain of struggle over the sociometabolic transition and the strategic agency of "middle-ground" organisations such as IPE and Unite. Starting from that analytical framework as a propedeutic for empirical research, in the second phase, my research engaged the two organisations directly through fieldwork. My primary focus was on the organisation-field dynamic: how do IPE and Unite work to produce expertise and work with their social constituencies to affect the field of environmental action (rather than the individual-organisation dynamics shaping these entities from within). Once completed, the fieldwork and co-research with these actors then served to expand the initial theoretical conceptualisation and to speculatively assess the future prospects of their respective environmentalisms.

The methodology I have selected is aimed at building an applied theory of ideational and material struggles over sociotechnical and sociometabolic transition from within the present conjuncture and from the standpoint of these actors. It develops an interpretivist institutional analysis of how organisations such as IPE and Unite can contribute to shifting the framing of environmental action and steering it onto another pathway. My principal approaches were iterative theory-building and embedded case studies. Methods I have used in conducting these case studies, although transformed in their implementation by the intervening circumstances of the COVID-19 pandemic, included an analysis of the primary and secondary literature, participant observation, semi-structured interviews, and co-research, allowing for a pluriperspectival capture of the strategic, epistemic, and social agency of these organisations. Furthermore, I engaged the organisations in the spirit of militant research, seeking to directly support and extend their proposals and actions developed in opposition to the dominant ecological modernisation framing.

## Positionality of research

Viewed in terms of my positionality as a researcher, the motivating factor behind this thesis is rooted in militancy and is collectively determined. The initial proposal for this research has developed from my experience of joint activist work with environmental groups and trade unions in Croatia over the last twenty years. In the early 2000s, the interests of the collectives I was part of were in technologies, politics, and the commons. Building on that work on digital commons, these collectives started to interrogate urban redevelopment processes that in the mid-2000s transformed formerly societal goods under Yugoslav socialism into new frontiers of enclosure and accumulation. As part of the Right to the City movement in Zagreb, we helped initiate a series of mass mobilisations between 2006-2015, which contested the privatisation of public land, national highways, and public services. Over the course of these mobilisations, Right to the City collaborated closely with Croatia's largest environmentalist organisation and Friends of the Earth affiliate, Green Action, and several public-sector trade unions [@MedakIndependentCulturalWork2017].

Toward the end of that period my intellectual interests shifted toward researching the socioeconomic drivers of technological change. This led to my being asked on repeated occasions by our allied environmentalist organisation to present on the subject of technologies in relation to the planetary ecological crisis. In 2016 at the Green Academy summer school and at the International Degrowth Conference, both co-organised by IPE, I gave talks on "Technologies for an Ecological Transition" [@medak_technologies_2018], presenting my research on the affordances and pitfalls that alternative technologies present for a transition to a post-growth metabolism, with a particular focus on what actors from the semiperiphery could do and should strive for. This was my first foray into the research interests that have led to this thesis. Since then I have become increasingly involved in environmental activism. This was the primary factor motivating me to better understand the strategic capacity that actors such as environmental groups and trade unions have in shaping the future direction of technological change while ensuring that that change can also lead to more sustainable and just socioecological arrangements than the present extractivist, growthist, and uneven capitalist development. While this thesis provides an appreciative account of the work of environmental groups and trade unions, it also wants to contribute to their collective analysis a theoretically-grounded and cautious reading of structural and conjunctural constraints and opportunities in contesting the status quo of environmental (in)action.

Furthermore, the work on this thesis has ramifications beyond research and environmental activism. Over the last five years, through my involvement with the municipalist green-left platform Zagreb je NAŠ! and the national green-left platform Možemo!, I have become a member of the working bodies of a political party that has recently, and unexpectedly, gained significant leverage on local and national environmental politics. In the 2020 national elections Možemo!-led coalition won five seats in the parliament, and in the 2021 municipal elections Zagreb je NAŠ! won the mayoral position, almost a majority in the city assembly, and majorities across most neighbourhood and district councils in the city of Zagreb. Currently, I am their programme coordinator and a member of the green transition working group. Three aspects of the research I have done for this thesis bear on that political work. Firstly, in a context of environmental policy dominated by a technology-first approach, frequently agnostic toward the social aspects of transition, my research highlights the primacy of social processes driving technological change and the diverging social outcomes resulting from different technological choices. Secondly, it suggests that rapid decarbonisation, ecosystem restoration, and other urgent measures to prevent further destabilisation of Earth's biophysical processes necessitate changes to how societies structure the provisioning for their members' needs. Thirdly and decisively, it indicates that such transformations need to be first experienced before they can gain popular acceptance and democratic legitimation. In that collective familiarisation with new, more sustainable and just modes of living, social actors such as environmental groups or labour organisations, operating in what I have called the "middle ground", where they shape quotidian practices and common senses — play a catalysing role. The implication is that a pivotal part of transformative environmental politics should be to strengthen the strategic agency of these actors and the practices they are developing in their particular social contexts.

## Research objectives and questions

While the initial motivation for this research might be activist and political, the invocation of "political steering" in the subtitle of this thesis refers rather to a larger process of re-politicisation. The subtitle — can the planetary technosphere be steered politically toward a post-capitalist social metabolism? — aims at reconsidering how the dominant forms of environmental action instituted by (trans/sub)national governance can be effectively contested, and how they can be reoriented from a market, bureaucratic, and technological logic to a democratic-redistributive one. **The overall goal** is to develop understandings of the strategic capacity of organisations such as environmental groups and trade unions to do so — and to do so by shifting the environmental action away from the market-driven technology-first approach toward fostering more sustainable and just social metabolisms.

However, directly researching these organisations, with whom I also share activist and political causes, could easily lead to a potentially voluntarist assessment, if their strategic capacity to steer toward a post-capitalist social metabolism were not analysed within the constraining and enabling factors imposed on them by the present social metabolism and the structures of the capitalist economy and the state. The research, therefore, pursues the overall goal through three related research objectives.

**The first objective** is to provide an *historical analysis* of how the fossil-fuelled industrial-capitalist social metabolism emerged, evolved, and consolidated. Specifically, it is to analyse *what processes have driven the transitions to that presently dominant sociometabolic regime, and, in turn, what impediments does that regime impose on achieving sustainable and just social metabolisms in the future?* The technological, energetic, material, and socioeconomic lock-ins, inherent to that regime, are already an immense obstacle for a technology-first transition aimed toward greening the existing technological infrastructures, let alone for alternative proposals that might want to reduce energetic, material, and economic impacts. Therefore, understanding the scale, the social processes that have led to that scale, and the arrangements that sustain that scale is necessary to situate the strategic agency within the material and social complexities of transition from one social metabolism to another.

**The second objective** is to elaborate elements of a *theory of agency in structure* and *political epistemic middle ground* delimiting the strategic capacity of various actors within political, institutional, and social processes shaping and driving sociotechnical and sociometabolic transitions. This conceptualisation devises a framework to comprehend specifically the agency of environmental groups and trade unions, by asking the questions: *Can social actors that are neither governments, corporations, or scientific bodies be catalysts of sociotechnical and sociometabolic change? Can they envision such transitions, produce the necessary expertise, and shift their dominant framings in significant ways? Can they engage their social constituencies to ground environmental action in their lived experience and conditions of inequality impacted by environmental policies?* This theoretical conceptualisation draws out the strategic opportunities afforded to the "middle-ground" actors by the ecological imperatives of social development that are weaking the capitalist economy's determining power over transition and open avenues for framing struggles that can contest the adequacy of technology-first strategies.

While the first two objectives are aimed at a more general inquiry of what are the enabling and constraining factors to re-politicise the environmental action, **the third objective** is to provide an account of *how organisations attempt to do this concretely*. That is, the objective is to engage an environmental group in Croatia and an industrial trade union in the UK, analysing and contributing to their strategies and alternative proposals in contesting the dominant market-driven technology-first approach. The fieldwork with these organisations considers *how do such actors concretely envision and act to shift the framing of environmental action toward a post-capitalist social metabolism? How do they ground these proposals in the practices of social constituencies they work with? And what are the future prospects of their proposals?*

How these research questions have evolved is discussed in more detail in the next chapter on methodology. Historical, strategic and epistemic analyses corresponding to objectives 1 and 2 are provided in chapters 3, 4 and 5, whereas the engagement with the IPE and Unite corresponding to objective 3 is provided in chapters 6 and 7. I will return to explain this structure in the thesis outline below.

## Gap in the existing research and contribution to knowledge

While I indicated earlier that this research is pragmatically motivated, seeking to contribute with its analysis to collective activist efforts, the question remains: where is it situated and what does it contribute in terms of scholarship?

The starting point for my inquiry lies at the intersection of theories investigating technological change, collective action, and ecology. It takes a synthetic approach, drawing on diverse bodies of research on these subjects, *to construct a comprehensive perspective on the problem of how large-scale transformation of the capitalist social metabolism can be instigated by a situated strategic agency of social actors*. This comprehensive perspective integrates both the present conjuncture and the standpoint of the particular organisations I engage with.

Concretely, my inquiry is situated within the research paradigm of sociometabolic transitions that has now been three decades in the making, most notably in environmental history [@cronon_natures_1992; @pomeranz_great_2000; @barca_energy_2011], environmental humanities [@chakrabarty_climate_2009; @ghosh_great_2016], ecofeminism [@merchant_theoretical_1987; @plumwood_environmental_2005; @haraway_staying_2016; @tsing_mushroom_2015; @barca_forces_2020], ecological Marxism [@burkett_metabolism_2006; @foster_ecological_2011; @huber_lifeblood_2013], and social ecology [@sieferle_subterranean_2001; @krausmann_global_2008; @fischer-kowalski_analyzing_2011]. This literature is discussed, commented and built upon in my historical account of the rise of industrial-capitalist social metabolism and the dominance of fossil fuels.

Furthermore, it is situated within subdisciplines in technology studies theorising the determining role of technologies in social change and the determining role of social relations on technological change — including the social construction and social shaping of technology [@schwartz_cowan_more_1985; @hughes_networks_1993; @mackenzie_knowing_1998; @mackenzie_social_1999], science and technology studies [@callon_techno-economic_1990; @latour_we_1993; @law_aircraft_2002; @sismondo_introduction_2009], and Marxian critique of technology [@slater_outlines_1980; @smith_does_1994; @davis_cutting_1998; @feenberg_transforming_2002; @noble_forces_2011; @dyer-witheford_cyber-proletariat_2015]. I consider these theories in combination with theories analysing the interactions of social actors, institutional orders, and social structures within the capitalist state, specifically structuration theories [@giddens_constitution_1984; @sewell_theory_1992], the strategic-relational approach [@jessop_state_2008], and institutional logics approach [@friedland_bringing_1991; @thornton_institutional_2008]. By combining sometimes complementary and sometimes contrasting theories of agency, technology, and structure in novel ways, I build my own analytical frameworks that are specific to the "middle ground" organisations I am researching and to the conjuncture in which they have to act.

Finally, it is situated in a growing body of research, much of it participatory or ethnographic, that has been carried out on the role of activism and trade unionism in the global environmental arena [to mention some of the most notable: @reitan_climate_2012; @klein_this_2014; @hampton_workers_2015; @barca_working-class_2018; @malm_how_2021; @riofrancos_resource_2020]. However, there is limited research on the shaping capacity of environmental activism and trade unionism on the sustainability transition from both technological and strategic perspectives [@rathzel_trade_2013; @backstrand_climate_2016; @dawson_peoples_2020]. My thesis sits in this gap and seeks to contribute original theorising of that strategic capacity in the present conjuncture.

The thesis contributes to that scholarship in four principal respects. Firstly, by combining these various strands of theorising in novel ways, *I devise two related analytical frameworks, one of the larger structural terrain of agency in sociotechnical transition and another of the strategic terrain for the "middle-ground" organisations to shift the framing of that transition*. These models add to the understanding of what are the structural factors that limit and enable actors that are neither governments, corporations, nor scientific bodies to disrupt the dominant forms of environmental (in)action and transform these forms from the bottom-up. There is an urgency and necessity to analyse their strategic capacity in the present conjuncture, which is defined, paradoxically, by the increasingly evident faltering of the (trans/sub)national governance process to limit the global warming to 1.5°C or 2°C above industrial levels, and, at the same time, the electoral defeats of the proponents of democratic and redistributive environmental politics of green new deal in the US and the UK. The theory-building I undertake in this thesis is an effort to draw out elements on which to debate strategic openings in that seeming impasse.

Secondly, *I offer an original perspective on how these actors' positionality allows them to work with their social constituencies to ground environmental action in distributive conflicts and the lived reality of these constituencies*. While climate change policy is framed in terms of long-term collective action of global society that seemingly does not have an immediate impact within societies, the recent scholarship indicates that the effective national climate action hinges on distributive conflicts between the polluters and the rest [@aklin_prisoners_2020; @mildenberger_carbon_2020]. The central question is who bears the existential cost. The answer is that the masses are made to carry these costs either through climate-driven natural disasters or the rising carbon prices of energy and essential goods. I extend this focus on distributive conflicts by elaborating that the "middle-ground" organisations are in a unique position to make those conflicts manifest and ground their work in the socially unequal and environmentally destabilised conditions affecting the contexts from which they operate. They can do so by working with the communities to translate the alternative proposals they develop into their lived reality and to translate their lived reality into their alternative proposals — and from there further into the framing struggles pursued on the institutional terrain of (trans/sub)national climate governance. From the engagement with these organisations and the evidence I bring together of the epistemic, educational and organising efforts they are developing with their constituencies, I contend they can contribute to shifting the environmental action from a market-centred top-down logic to a democratic-redistributive bottom-up logic.

Thirdly, *I contribute to the understanding of why both the existing technological infrastructures and the ongoing sociotechnical transition are susceptible to contestations that intervene locally to affect significant shifts in the larger political terrain*. I argue that the blockade, but equally mass organising and framing struggles around and against particular technological infrastructures and particular sociotechnical changes matter to the re-politicisation. Of particular interest are under-researched parallels between Big Tech and Green Tech, at a moment when Big Tech companies, characterised by a resistance to unionisation, are increasingly moving into and setting the blueprint for the Green Tech industries. I outline some of the valuable lessons that can be drawn from contestations against Big Tech for working-class environmentalism.

Finally and relatedly, I argue that for reasons of accumulated pollution and destabilisation of Earth's biophysical processes, a condition that Herman Daly has qualified as a "full world" [@daly_economics_2005], the future is not an open horizon where all transition pathways are equally possible and adequate, as the seeming flexibility of global policies and nationally determined contributions might suggest. Through my analysis I add to the understanding of why alternatives to ecological modernisation are necessary and how they can be adequate — by proposing strategies prioritising equitable wellbeing and environmental stability over a continued economic growth. *I will contend that achieving environmentally livable and socially just futures in a destabilised planetary ecology requires both careful and urgent experimentation with alternative pathways, of which technological change is only one aspect among the many-sided and far-reaching economic, political, and social transformations*. While that might be evident from the degrowth perspective, it is less so from a trade-union perspective. But I propose why that might need to change. Therefore, I provide a speculative analysis of some of the proposals and alliances that the social-movement and the working-class environmentalisms can develop in the present conjuncture to again shift the terrain of struggle over environmentally safe and socially just futures.

## Thesis outline

The next chapater, **chapter 2** outlines my methodology. It expands on the positionality and objectives discussed in this Introduction to elaborate how the stepwise development of research objectives and analytical framework served to select the two organisations for my case studies and prepare the fieldwork. And, in turn, how my interpretivist analysis of the agency of those two organisations worked back to inform a theory of sociometabolic transformation in the focus of this thesis. My principal methodological approaches were iterative theory-building and embedded case-study research. While doing fieldwork, I have engaged the organisations in the spirit of militant research, attempting to directly support and amplify their counterproposals to the hegemonic framing of ecological modernisation. The combination of these approaches was needed to situate the first-hand account of their agency gained through fieldwork within the structural analysis of technological, economic, and institutional factors that constraint and enable that agency, while allowing the militant motivation that has led to this research to extend into an assessment of what prospects their work might have in the future.

The methodology discussion segues into three chapters in which I develop my analytical frameworks from historical, strategic, and political-epistemic discussions. Throughout these chapters, agency aimed at sociometabolic transformation is analysed against the constraining and enabling factors of technology and the capitalist state.

**Chapter 3** harks back to a history of systemic, technological, and energy transitions from the 16th to the late 20th century that have led to the presently dominant fossil-fuelled industrial-capitalist social metabolism. It retraces entwined transitions from feudalism to capitalism, from renewable energy to first coal and then oil, from agricultural steady-state to globalised industrial growth, from the conservation of energy to inefficient large-scale energy systems, and from the early colonial capitalism to neo-imperial unequal ecological exchange. The central question I explore in this genealogy is whether these historical transitions were driven by technological advances or social antagonisms, indicating that social antagonisms and distributive conflicts have been key factors in the past transitions. The chapter's objective is to provide an account of the challenge that the presently dominant social metabolism sets before any future transition.

**Chapter 4** parallels that genealogy with a theoretical analysis of strategic agency in the structure of the present green transition. Discussing technological determinism, agency in stucture, and a critical theory of technology, I propose a framework to analyse agency in and against the social structures of the state and the capitalist economy. The framework indicates openings for actors other than corporations, technologists or governments to disrupt and change the course of sociotechnical and sociometabolic change. However, the lock-ins of fossil-fuelled technologies and the asymmetries of power result in significantly different capacities of social actors to effectively impact these transitions. To bring the chapter to a close, I argue that despite these asymmetries, the dependence of technological systems on regulatory arrangements and energy infrastructures makes them susceptible to direct political contestation, thus producing an avenue for non-linear transformations through three vectors of disruptive agency: blockade, organising and framing struggles.

While chapter 4 concludes with a reflection on the brittleness of technological infrastructures to the acts of blockade, **chapter 5** focuses on the other two vectors of disruption: framing struggles and organising. I propose a framework to analyse the "middle ground" of agency between the (trans/sub)national climate governance and social constituencies. The framework addresses the positionality of environmental groups and trade unions within the broader context of knowledge production and distributive conflicts in climate action. These organisations, although neither scientific institutions nor policymaking bodies, do engage in research activities and produce their own expertise to translate environmental science into the lived reality of their constituencies — and vice-versa. To elaborate how the epistemic politics of such organisations can be reconciled with the objectivist principles of science, I analyse their work through the lens of feminist standpoint epistemology and the "post-normal science" necessitated by the urgency of the crisis. Finally, I contextualise their work on distributive conflicts within the broader climate change politics, asserting that the science-based climate action is rooted in the post-WWII liberal international order but is, at the same time, subverted by the economic neoliberalisation and the inequalities this order has given rise to. The groundedness in ideational and material interests of their social constituencies thus makes these actors into potential proponents of a pro-environmental transformation from below.

The three chapters focusing on theoretical conceptualisation segue into two case study chapters that draw on my fieldwork with the IPE and Unite. Both chapters include three macro-segments: a discussion of particular environmentalism, an analysis of the organisation and my engagement with the organisation, and a speculative exploration of the limitations and opportunities their form of environmentalism brings to the present conjuncture.

The first of the two, **chapter 6**, developed during my fieldwork with the IPE in 2019, starts by detailing the emergence of degrowth as a social-metabolism-oriented environmentalism. Degrowth coalesced in parallel into a global movement and a research project, developing proposals, theoretical and practical, on how to transform the destructive sociometabolic patterns of affluent societies by lowering the throughput of energy and matter, redistributing social wealth, and allowing a pluriverse of material and epistemic routes for societies outside of capitalism. From this general outline of degrowth environmentalism, the chapter moves on to the actions and positions of IPE. My principal engagement with the organisation was the participation in the development of a Degrowth Doughnut aimed at overcoming the opposition between nature and society and at providing a tool for democratic degrowth within different social metabolic units. The chapter concludes with a reflection on how degrowth is proposing a real-utopian horizon of sociometabolic transformation built on prefigurative practices, an approach taking the "full world" of destabilised planetary boundaries as truly limiting, and developing policies, practices, and tools to transition societies toward a good life within planetary boundaries for all.

The second case study, the basis for **chapter 7**, was initiated in late 2019 and was unexpectedly disrupted by the COVID-19 pandemic. Here I first outline the elements of working-class environmentalism, conceptualising the separation of internal from external nature within capitalism, as well as the various forms of the environmental vulnerability of the working class. From there, I analyse the strategic agency of the working class within the economic and environmental domain, arguing that organised labour developed forms of power from below that have significantly disrupted the direction of social development to create more democratic and environmentally safer societies. My analysis of Unite's environmental strategy is situated in this history, outlining its ambivalent positioning that includes both transformative components of green industrialisation and conservative components of support for polluting industries. The threat of the working class losing once again in the next transition (as it did in the UK's transition from coal) calls for a just transition that will provide security and jobs for workers and their communities as the fossil economy is phased out. The chapter concludes with a discussion of the waning political fortunes of the green new deal proponents who have argued that addressing social inequalities is a necessary prerequisite for climate action. I contend that given the labour movement's fragmentation, resulting from technological change, the onus is on the proponents of other environmentalisms to support the unionisation and help trade unionism again gain ground to advocate for more radical and community-oriented environmental proposals in return.

In the concluding chapter, **chapter 8**, I return to my initial research questions to argue how the take-aways from the two case study chapters, as well as from the historical, strategic and political-epistemic inquiries in earlier chapters, combine in novel ways to contribute to knowledge of the ecological agency of the "disruptors" of the market and technology approach. The conclusion suggests further avenues of research, particularly indicating the significance of "middle-ground" actors as the world moves from the expectations of climate change mitigation to the realities of climate change adaptation.



[^1.1]: For the purposes of this thesis, technology is understood as *interlocking, formally organised material and symbolic systems that constitute and structure sociometabolic exchanges between human societies and non-human nature*. The thesis repeatedly resorts to a few foundational concepts: technology, the capitalist mode of production, social metabolism, planetary boundaries, and environmentalism. Their definitions are provided in Annex I.

[^1.2]: The exponential expansion of microcomputing and digital networks has come to shape the contemporary popular expectations of sociotechnical transitions. Digital technologies are perceived as maverick forces of the "creative destruction" of old oligopolies and bureaucratised institutions. Some of the transformations facilitated by digital technologies have indeed been unprecedented. Computerised control, coordination, and optimisation of geographically distributed processes have accelerated the integration of the post-1989 global free markets, the relocation of manufacturing to South East Asia, and the creation of global just-in-time supply chains. These transformations only pale in comparison to the changes in private and mass communication. These disruptions, however, have not come without significant political destabilisation and growing redistribution to the top, drawing an increasing public and regulatory scrutiny.

[^1.3]: Throughout this thesis I will use *italicised text* to highlight definitions, insights, and conclusions that advance my argument.

[^1.4]: For a definition of "social metabolism" see Annex I.

[^1.5]: For a definition of "environmentalism" see Annex I.
