# Conclusion

\minitoc

## Introduction

Over the last two chapters I have explored the work of two organisations rooted in two different varieties of environmentalism — an environmental group rooted in degrowth with a focus on research and education and a large industrial trade union rooted in working-class environmentalism with a focus on workplace bargaining, politics and industrial policy. Specifically, I have examined their strategies holding the potential to *disrupt the dominant market-driven technology-first approach to environmental action and thereby to re-politicise and re-democratise the (trans/sub)national environmental governance*. Drawing on semi-structured interviews, an analysis of primary and secondary documents, and joint research with these organisations, I have argued that they *engage the terrain on which climate policy is promulgated as epistemic actors and work with different social constituencies to instil distributive justice into climate action*. IPE, as an epistemic actor, through its work on the Degrowth Doughnut, is developing a model for societies to measure and benchmark a multiplicity of social and biophysical factors defining their social metabolism. This could help countries, regions, or municipalities chart their unique transition pathways from a high-throughput capitalist social metabolism to a plurality of sustainable and just futures (see section 6.4). Unite, conversely, is proposing a green industrialisation or a green new deal. This consists of a balanced energy policy, provisions for a just transition, the creation of climate jobs and, in a conducive progressive political context, a nationalisation of sectors such as railways. Through its political work by way of the UK Labour Party and industry bodies, it is advocating for a state-coordinated sociotechnical transition that would, instead of blindly following the dynamics of markets, prioritise the security of workers and their communities (see section 7.4).

Secondly, I have argued that these organisations also engage diverse social groups as *organising and mobilising actors* (see sections 6.3.1 and 7.4.1), including activist organisations, local communities, and political parties in IPE's case, and union members, their communities, and the UK Labour Party's constituencies in Unite's case. In this role, they are working with those constituencies to re-articulate their understandings, material interests, and practices to align them with the prospects of a transition to sustainable and just technological and institutional systems of provision for social needs. And, working in the opposite direction, they translate the material and ideational interests of those groups into framing struggles. In so doing, they are seeking to ground climate action in the lived reality of highly unequal societies and to democratise otherwise technocratic environmental governance (see sections 6.4.1 and 7.4.3).

The efforts of these organisations to shift climate action toward a democratic-redistributive logic have unfolded against an ecological modernisation framing that has, at least since the Kyoto Agreement, coalesced into the hegemonic paradigm for climate action (see section 5.2). However, there are concerns that this paradigm's market-driven technology-first approach to rapid decarbonisation is not adequate or timely enough to achieve the ambitious goals of halting global warming to 1.5°C or 2°C above the pre-industrial levels. The current decarbonisation policies have a 50:50 chance of leading to a warming of 2.7°C or greater [@climate_action_tracker_cat_2021]. Their implementation would require a ramp-up in renewables, carbon capture, and biomass capacity to compensate for past and future fossil-fuel burning at historically unprecedented and currently undocumented rates [@loftus_critical_2015; @allwood_technology_2021]. Meanwhile, carbon markets are reinforcing lax, least-cost technological changes instead of effective technical transformations paired with just social policies and new patterns of social provision.

Against this potential shortfall in climate change mitigation and a growing destabilisation of ecosystems, accompanied by uneven social and environmental impacts, the thrust of my argument in this thesis is that *environmental politics can not be isolated from distributive conflicts* (see section 5.5). The backlash against carbon taxes, as evidenced in the "yellow vests" protests, attests to that. In and between unequal societies, the mitigation policies and climate impacts are already resulting in widely diverging effects, unleashing democratic-redistributive struggles and necessitating democratic-redistributive politics. As these effects gather pace with the growing price of decarbonisation and the growing cost of repair from environmental disasters, the work of organisations such as the two I have examined in this thesis, as well as the work of proponents of degrowth and working-class environmentalisms at large, might become increasingly urgent and called for. I have found that their future-oriented proposals, necessarily speculative, experimental and prefigurative, benefit the collective capacity of industrial capitalist societies *to envision and build alternative pathways to environmentally livable and socially just futures*, should the market-driven technology-first approach continue to fall short on climate goals and an increasingly destabilised climate impose itself on societies (see sections 6.5 and 7.5).

Although I have concentrated in my inquiry on the strategies that disrupt the technology-first approach, I have suggested that in that change of pathways, *the direction of sociotechnical transition will also have to be changed so as to become targeted at the highest-effect decarbonisation measures* and become threaded together with "rapid, far-reaching and unprecedented changes in all aspects of society" [@ipcc_summary_2021] (see section 5.4). Speaking with Andrew Feenberg [-@feenberg_questioning_1999], the instrumental rationality of the capitalist, market-dominated technological development will have to be replaced by democratic rationality. To institute a democratic rationality, we might need tools such as doughnuts to steer sociometabolic transformation at various scales, including regional and municipal, from where distributive demands and democratic participation can be instituted from the bottom up. However, degrowth scholars argue that to limit the throughput of energy and matter that cause environmental degradation, the expectations from technologies to deliver on the ever-growing demand for energy and matter might need to be lowered in affluent nations and compensated by the forms of provision for wellbeing through social redistribution.

A fundamental insight from the prefigurative, future-oriented proposals of the organisations examined in this thesis is that *change has to be experienced in order to become democratically more feasible*. This is the task that both IPE and Unite attend to through their work with their constituencies. By empowering, largely through education, these constituencies to engage their own workplaces, social institutions they interface with, and their social contexts from a perspective of environmental sustainability, they can come to desire and seek to determine a different structure of social needs and provision for their fulfilment, *collectively becoming an agent of sociometabolic transformation*.

## Iterative theory-building

While the preceding paragraphs provided an abridged version of my fieldwork findings with *the concrete why, who, and what* of the strategic agency of IPE and Unite, I have in this thesis in equal measure *theoretically conceptualised their type of agency in more general terms*: what are the factors that enable and constrain the strategic capacity of "middle-ground" organisations such as IPE and Unite to instigate and shape the macro-social transformations of the industrial-capitalist social metabolism, considered from the perspective of the institutional ensembles of the state and the capitalist economy (see chapters 4 and 5).

Methodologically, I approached this theoretical conceptualisation of strategic agency through iterative theory-building (see chapter 2). My *initial research question*, contained in the subtitle of the thesis, asked whether the planetary technosphere can be steered politically toward a post-capitalist metabolism. My approach concentrated on how organisations that are neither governments, corporations, nor institutions of science can impact the processes of technological change directly to help along a sociometabolic transition. From that initial problem-setting, the inquiry evolved into an analysis focused on how a goal-oriented transition imposed on technological change to rapidly lower societal impacts on climate can open up a broader terrain of agency for these organisations: *a terrain that is not limited to the strategies of impacting technological change but rather allows these organisations to contest, re-articulate, and shift the framing of larger sociometabolic transition and embed it into their respective social contexts and material realities*. Starting from this refinement of the research goal, I have evolved two analytical frameworks to gain a comprehensive perspective of the capacity of these organisations to do so, combining in novel ways several complementary theoretical approaches: ecological Marxism, environmental humanities, Earth system science, science and technology studies, critical theory of technology, strategic-relational approach, and institutional logics theory. Using these analytical frameworks, I developed and conducted my fieldwork, in the course of which I also sought to contribute, in the form of militant research, to the work of the organisations I had selected for my case studies.[^8.1] Finally, drawing on the analysis of their work, I have concretised and expanded that structural conceptualisation with a conjunctural assessment of the prospects of their respective environmentalisms in the present moment.

Once that overall goal of the research for this thesis was set and refined, the research then pursued *three objectives* responding to the following three concatenated questions:

> 1. What processes have driven the transitions to the presently dominant sociometabolic regime, and, in turn, what impediments does that regime impose on achieving sustainable and just social metabolisms in the future?

> 2. Can social actors that are neither governments, corporations, or scientific bodies be catalysts of sociotechnical and sociometabolic change? Can they envision sociotechnical and sociometabolic transitions, produce the necessary expertise, and give direction to such transitions in significant ways?

> 3. How do such actors concretely envision and shift the framing of climate action to steer toward a post-capitalist social metabolism? How do they ground these proposals in the practices of the social constituencies they work with? And what are the future prospects of their proposals?

The first question I have dealt with primarily in chapter 3, the second in chapters 4 and 5. The exploration of these questions laid the ground for my analytical frameworks. The last of the three objectives I have dealt with in my case-study chapters 6 and 7.

## Summary of key arguments

These are the key arguments I have made in those topical chapters:

In **chapter 3** I established, through a genealogical account, that coal-fuelled industrial capitalism, with its novel energy- and matter-intensive social metabolism, emerged from an interaction of class struggle, technological change, and ecological unequal exchange in the emerging colonial capitalism. I further retraced the ensuing energy transition to oil and attendant political developments, elaborating that the responses of capital to the disruptive power of organised labour to sabotage industrial infrastructures have in the post-WWII period consolidated in the internationalisation of fossil-fuelled economies governed by an imperative of growth, a continuously increasing energy demand dependent on centralised energy systems, and a militarised global governance of energy supply — instead of taking a more decentralised and irenic path, particularly after the 1970s energy crises, by way of renewables. These processes set off a trajectory of socioeconomic development driven by technological modernisation that has, over a few short decades, resulted in environmental degradation at the planetary scale.

In **chapter 4** I posited that technologies are structuring social metabolisms as the means by which human societies appropriate and transform nature to reproduce themselves. The attained world-spanning scale of interlocking technological systems that have evolved since the 19th century, their ever-growing appropriation of energy and matter from nature, and their entanglement with state-regulated capitalist accumulation have created material, energetic, technological and socioeconomic lock-ins that constrain future sociotechnical and sociometabolic transitions. However, as the shift from technological to ecological modernisation imposes environmental goals on future social development, I have argued that this weakens the strongly determining effect that the capitalist economy has over these transitions. That weakening strengthens, in turn, the organisations that are neither states, corporations, nor scientific bodies to use the institutional ensembles of the state to shift the understanding of the inchoate sustainability transition from a market-driven logic to one that is more strictly oriented toward achieving ecological safety and social justice. Along with the sabotage of energy and technology infrastructures, I have proposed to view these framing struggles and the organising around distributive conflicts with social constituencies that these entities do as the three "vectors of disruption" of the dominant industrial-capitalist social metabolism and the market-driven technology-first approach to transforming it.

**Chapter 5** served as a bridge to the case study chapters as I concretised the strategic capacity of actors such as IPE and Unite in terms of operating in the "middle ground" between (trans/sub)national climate governance, primarily mediated through the institutional ensembles of the state, and the social constituencies affected by distributive conflicts of climate (in)action. In the analytical framework I devised, the "middle-ground" actors are epistemic actors, members of an expanded peer community in a situation of crisis that calls for a "post-normal science", engaging from their socially situated standpoint in negotiations and struggles to push the governance institutions to move away from the market logic to a democratic-redistributive logic. As climate governance is, in my analysis, beset by democratic deficits and suppressed distributive conflicts, the "middle-ground" organisations enable the participation of various social constituencies in climate action by working with them to re-configure their collective experiences and practices so that they can be aligned with alternative pathways to sustainability and, in turn, translating their material and ideational interests into framing struggles. The opportunity to change the dominant market logic and change how social constituencies associate with alternative pathways might be catalysed, so I propose, by events that make visible the shortfalls of the market-driven technology-first approach to climate action and the growing impacts of climate change — and thus make evident the urgency and necessity of alternative pathways. These are the events that might make the currently counterhegemonic alternatives institutionally and democratically more feasible.

Over the next two chapters I built on my fieldwork with two "middle-ground" organisations and the environmentalisms foundational for their work, developing a future-oriented reflection on what is to follow should the course of events indeed open towards opportunities for change.

In **chapter 6** I thus contended that degrowth environmentalism presents a radical challenge to the market-driven technology-first framing, as it questions its fundamental assumption of economic growth. Instead, it proposes to limit the throughput of energy and matter in affluent countries while redistributing social wealth, thus leaving enough carbon budget to allow all societies to pursue their own pathways to wellbeing within planetary boundaries. The chapter highlights IPE's situatedness in a post-socialist semiperiphery, characterised by greater sufficiency-mindedness and acceptance of degrowth due to a disenchantment with the post-socialist transition. IPE is advocating a downscaling of climate action to regional and municipal levels, where it can be more easily democratised and transformed, and to that effect it is conducting its own research and educational activities with a variety of activist and political actors across Croatia and neighbouring post-socialist countries. As in the case with much of the degrowth movement, IPE has concentrated on political-epistemic activities, trying to transform the field of climate action to abide strictly by planetary boundaries whose destabilisation confronts us with what I have termed a "rejective future", i.e. a narrow band of transformation in a destabilised planetary ecology that is highly selective of what strategies will allow sustainable and just futures for all. However, the degrowth movement has constantly been working in parallel to devise prefigurative and experimental practices that might foster not only sufficiency but also adaptation and resilience to disruptive climate change moving forward.

**Chapter 7** posits that working-class and social-movement environmentalisms meet on a common ground once the environmental degradation reaches a scale where it affects the world's entire working class in an uneven yet combined way. By adumbrating a theory of nature in capitalism, I argue that the stability of ecosystems for human societies cannot be fully internalised as costs into the present economic system, and that their value and the safety from the environmental vulnerability of the working class is instead decided on the political terrain. In this chapter I situate the strategic agency of the working class to effect macro-social change in its interdependent and disruptive power that has risen with the concentration and upskilling of the working class in industrial capitalism and declined with further technologisation and the disaggregation of production along global value chains. Unite, the subject of my research, is a 1.4 million-strong industrial trade union advocating a state-coordinated just transition with a strong component of, but also caution toward technological restructuring. In its work with union members, it has relied on educational activities and environmental representatives in the workplace to make workers agents of environmental change. In its political-epistemic work, it has relied largely on its formal affiliation with the UK Labour Party, which allows Unite to actively shape the political terrain at a national level. Nevertheless, there is a traumatic historical experience of the transition from coal under Margaret Thatcher, and Unite's calls for a just transition have in the past fallen on deaf ears even with Labour governments. Unite is, therefore, unsurprisingly, engaging in policy and innovation processes to create lifelines for polluting sectors that could reduce emissions and keep them operating for a while longer so as to smooth out the disruptive effects of the sustainability transition on their members.

Still, in the runup to the 2019 national elections in the UK, Unite was willing to risk rapid decarbonisation to net-zero by 2030 if the project of transition could be politically nested in a promise of a green new deal. After the defeat of the green new deal political proponents over the course of 2019-2020, that again seems a waning prospect. In my future-oriented analysis, the faltering of the green new deal conjuncture calls for another effort of social movements and progressive political actors to recast the political terrain to support the strategic agency of trade unions, and another effort of trade unions to create community-oriented proposals for an equitable sustainability transition. Otherwise, with the rise of cleantech, the working class might again end up being delivered to a disruptive transformation, this time for the benefit of green growth. To conclude, I contend that, in the present, the unity of the two environmentalisms will not be a choice but a necessity.

## Heuristic contributions to knowledge

As outlined in the previous three sections, my thesis contributes to the understanding of the social agency of environmental groups and trade unions from the vantage point of how these actors respond to the hegemonic ecological modernisation approach in global environmental policymaking. That understanding is deepened through an analysis of their agency as political-epistemic actors and as actors working with different social constituencies, both to shape and redirect the sociotechnical and sociometabolic transformation of the currently dominant industrial capitalism.

However, throughout the course of this thesis, I have contributed several heuristic models and propositions, including:

An analytical framework (see section 4.1, *Figure 4.1*) that indicates changes in the strategic capacities of various social actors to impact the sustainability transition as the framing of social development shifts from technological modernisation to ecological modernisation. *The model indicates a weakening of the shaping and determining capacity of the capitalist economy and of the state over sociotechnical transition.* Given that future sociotechnical changes have to adapt to the imperatives of climate action, this leaves more strategic leeway for various social forces acting within and against the institutions of the state and the capitalist economy to challenge the adequacy and timeliness of the market-driven technology-first strategies to achieve rapid and far-reaching changes necessary for remaining within 1.5°C or 2°C of global warming by 2100. This also creates an opening to propose transformations that are not only technological but also economic, social, and political.

An analytical framework concretising the strategic terrain of "middle-ground" (see section 5.2, *Figure 5.1*) organisations nested between the institutions of (trans/sub)national climate governance and the social constituencies with their stakes in distributive conflicts over climate (in)action. *The model indicates how "middle-ground" organisations connect distributive conflicts with framing struggles to try to shift the dominant market logic of climate governance toward a democratic-redistributive logic*. The model accounts both for material and ideational resources that enable strategic agency and for change-catalysing events that might help bend the institutions and the attitudes of social constituencies toward accepting alternative pathways that allow for "rapid, far-reaching and unprecedented changes to all aspects of society" [@ipcc_global_2018].

A theorisation of a "rejective future" (see section 6.5.3), where future-oriented strategies face a horizon that is radically different from the horizon of technological modernisation and progress. *The transgression of planetary boundaries and the exhaustion of regenerative capacities make only some pathways of sociometabolic transformation livable for all of humanity*. A rejective future is unwelcoming, threatening with the uncertainties of tipping points, facing us with the risk of the uninhabitability of densely populated regions of the world. Unlike the seeming flexibility of global climate change policies and nationally determined contributions might suggest, the future is now rejective of many strategies of future-oriented action. Nonetheless, it calls for speculative, experimental, and urgent efforts in developing a plurality of sustainable and just pathways to achieve socially just and ecologically sustainable futures for all.

An assessment of the political terrain for such pathways after the defeats of the GND proponents in the 2019 UK parliamentary and 2020 US primary presidential elections (section 7.5.1). My assessment indicates that after the cycle of post-2008 mobilisations that worked around the rough consensus that urgent climate action needs to be wedded with redistributive action to overturn intra-societal inequalities, *there is a renewed need for the working-class and social-movement environmentalisms to forge a new mobilising narrative and forms of action*. It is more a diagnosis than a prognosis, requiring further development, research, and, most of all, new practical elaborations.

Finally, a proposition to consider ecological rationality as a common ground to compare different societies and social formations considering to what degree they are able *to conceive of and maintain in practice the dependence of their own society on a relative stability of Earth's biogeophysical processes* (see section 5.6). Judged on that criterion, capitalist cosmology can be deemed to be irrational, even in its decarbonised variant as it will still be breaching a number of other planetary boundaries.


## Avenues for further research

This thesis has explored the strategic capacity of "middle-ground" organisations to contest the hegemonic approach to environmental action, their capacity to enlist diverse social constituencies, and their capacity to shift the terrain of debate over environmental action to redistributive-democratic logic. My thesis has brought both the political conjuncture of climate change politics and the standpoint of the organisations I was engaging with to bear on that inquiry. The starting proposition focusing on disrupting the technology-first approaches in environmental action, the analytical frameworks I have developed in my theory-building, and the speculative conjunctural analysis lend themselves to further expansion as part of future research. The principal goals of my research — understanding how the existing social metabolism can be transformed through collective action to pave the way for environmentally sustainable and socially just futures for all — support the clear and urgent need for further exploration of these topics, pursuing several avenues of research:

Firstly, the research could be further extended through complementary case studies to yield a more structurally variegated and geographically inclusive analysis of the strategic agency of diverse social actors. The focus of the research has been on an organisation in the centre of capitalism and an organisation on its semiperiphery. Both countries, huge economic differences notwithstanding, are in the global order of economic disparity, middle-to-high-income economies (Croatia has been going in and out of that category over the last 15 years). However, they have had very different historical trajectories: one has been an industrial and colonial capitalist empire that has significantly deindustrialised, while the other a federal part of a subaltern and developmentalist socialist project that went through a turbulent period of breakdown in the 1990s to transition toward a monoethnic capitalist nation-state mostly organised around the service economy and rentierism. *Future research could extend my analysis of the "middle ground" to organisations beyond the capitalist centre and semiperiphery.* For instance, to one of the Latin American societies characterised by intense distributive conflicts between indigenous communities, farmers, the working class, foreign capital, and governments over extractive projects and environmentalism. In Ecuador or Bolivia the progressive governments over the last two decades were at least nominally committed to the environmental wellbeing of Mother Earth and inclusive social development, but faced the hard contradictions between the two in the global capitalist economy, where their social commitments can be advanced primarily by intensifying the extraction of primary commodities from nature [@riofrancos_resource_2020]. To add to the complexity, sociotechnical realities in the capitalist periphery are very different to that in the centre or semiperiphery. As the new green technologies are developed and disseminated from the capitalist centre, the peripheries of global capitalism are frequently stuck with an old, polluting, and extractive technological base [@emmanuel_appropriate_1982]. This "dirttech" development sets very different valences to how cleantech transition unfolding elsewhere and connected with it through globalised extractive and logistical chains can be politicised.

Furthermore, as I have discussed earlier (see section 5.6), the larger part of the global population lives in the commodity economy and depends on wages for at least part of their subsistence. *Future research could also benefit from exploring how the "middle ground" analysis of environmental action would stand the comparison with an outside perspective of the non-capitalist, subsistence communities and their positionality toward the capitalist social metabolism and (trans/sub)national climate change governance*. While capitalist development tends toward homogenisation of social life, these communities have highly heterogeneous modes of subsistence and modes of collective action organised by their particular natural environments and cultural and institutional arrangements rather than the capitalist economy and the state. Therefore, future research might focus on building conceptual frameworks to include these agencies.

In chapter 4 I have briefly touched on the forms of disruptive collective action that do not necessarily have a similarly stable organisational form as nonprofit associations or trade unions have — the disobedient interventions of land protectors and environmental justice movements blockading the polluting infrastructure and assailing the brittleness of highly complex technological systems, for example. Such actions, as Andreas Malm [-@malm_how_2021] has also recently noted, are actions of re-politicisation. *Future research could benefit from analysing such examples of disobedient mobilisations* aimed at vital energy and technology infrastructures.

Lastly, as concerns complementary research, my analytical framework could also be tested on the work of anti-environmental actors, such as lobbyist groups on behalf of polluting industries, conservative think tanks, or religious groups. In fact, the cause of progressive pro-environmental politics could benefit from a strategic and conjunctural analysis of detractors, many of whom are mobilising the working class fearmongering that the environmental action is ordaining austerity and further precarisation.

Secondly, the conjunctural analysis is a shifting terrain. In this thesis it is delimited, on the one side, by the potential failure of technology-first strategies to limit the global warming and ecological breakdown and, on the other, by the reaffirmation of these strategies in the wake of the political defeats of more progressive pro-environmental forces. However, as I was finishing writing up the thesis, a new international energy crisis and subsequently the war in Ukraine had started. While attempting to speculate if these events might speed up the transition away from fossil fuels is at the moment like looking into a crystal ball, they call for an expanded analysis of lock-ins into large energy systems, attendant militarisation and subsidisation of fossil capital, and the role of the states as guarantors of energy security and fossil capital. While I have touched on some of these issues (see sections 3.4.3 and 4.3), *developing a conjunctural analysis of what can be done by pro-environmental forces to attempt to shift the dominant responses to the war and the energy crisis that are now trying to substitute Russian fuels and minerals is of the utmost urgency*.

Thirdly, this thesis had taken a very specific optic on technologies when it defined technologies as "interlocking, formally organised material and symbolic systems that structure sociometabolic exchanges between human societies and non-human nature" and when it argued that the capitalist system of production is central to organising those exchanges and driving the growing throughput of energy and matter. In the Introduction I have invoked Stefania Barca's recent writing on the *Forces of Reproduction* [-@barca_forces_2020] to indicate that the sustainability of Earth's biogeophysical processes has rested and continues to rest on the contributions of relations other than those of capitalist production: socially and environmentally reproductive relations created and sustained by subsistence farmers, land protectors, care-labourers, other species, and ecosystems that have been there well before industrial revolutions. These other relations that one could qualify as relations of interdependence and of labour that goes into sustaining that human and non-human world have their own technologies — of reproduction, restoration, and repair. To name a few: technologies of agroecology and soil conservation [@puig_de_la_bellacasa_matters_2017], "soft-path" localised energy systems [@lovins_soft_1979], passive design architecture, indigenous technologies [@watson_lo-tek_2019]. And they could reappropriate and tinker to make sustainable the existing technologies of production [@mol_care_2015]. On some of those technologies of reproduction I have focused through the work I have been doing in parallel with my thesis on the project Pirate Care [-@pirate_care_network_piratecare_2018], looking at deeply technological practices of disobedient care-organising. However, the focus of the research in this thesis has been on the capitalist system and the technologies of production that structurally drive environmental degradation. *Exploring the world of technologies compatible with the transition to low-impact social metabolism and the technologies that sustain a good life for all within planetary boundaries would call for a novel research project.* And there is some urgency to such a project, as the technologies of social and ecological reproduction are increasingly becoming the technologies of future resilience and adaptation.

## A final thought

My research in this thesis has focused on the hegemonic and counterhegemonic strategies at the heart of the climate change mitigation policies. However, *the strategic agency of the disruptive "middle-ground" actors might grow in importance as the focus shifts from the mitigation of climate change to adaptation to the impacts of climate crisis*.

Barring significant change-catalysing events that would make the alternative pathways envisioned and developed by the "middle-ground" actors more democratically feasible, the world will continue on the pathway of flexible decarbonisation. This trajectory will in another decade break the world's carbon budget for 1.5°C global warming and see in the coming decades the global average temperature rise significantly, condemning many regions across the world to grave climatic stresses and societal destabilisation [@ipcc_summary_2021]. The growing impact of floods, fires, and crop failures will increasingly shift the focus from mitigation of climate change to socioecological resilience, adaptation, and repair. And while preventing further emissions will remain an ongoing task, the adaptation responses will lead to more downscaled distributive conflicts over who gets to carry the cost of disasters and repair within societies and communities. The democratisation of climate action will thus arguably become a higher priority, making the grassroots efforts of social actors nested between the institutional governance and social constituencies all the more significant — both in articulating these conflicts and helping social constituencies develop practices of resilience, adaptation, and repair.

With that downscaling of climate action, it will become an even greater challenge for societies to remain attentive and supportive of adaptation efforts elsewhere. As the global distributive conflicts over who bears the cost of mitigating climate change are likely to escalate further, the solidarity and internationalism over adaptation might end up being in an even shorter supply than today. An aspect of the growing gap between societies that do have the means to adapt and those that do not will also be technologies. Technologies for adaptation and repair will likely have to be more responsive to local environmental and socioeconomic circumstances, requiring a different approach to the development and deployment of technologies. For the affluent and struggling countries to have more equitable access to such technologies, a more transnationally cooperative, publicly-funded, and open process of innovation than the one driven by market competition and ecological unequal exchange might be necessary. *These challenges of solidarity, redistribution of costs, and access to technologies in climate change adaptation will make the re-politicisation of climate governance around distributive conflicts all the more urgent — and that is the task that the current technology-first approach helps policymakers avoid*. Their approach defers the costs into the future, assuming that they will be lower with further economic growth. While that is doubtful given the accelerating and accreting character of ecological destabilisation, technological change is certainly politically an easier sell to the voters and corporations than far-reaching changes to all aspects of society. While necessary, technological change thus also becomes a legitimational narrative and, as discussed with the example of negative emissions technologies (see sections 3.1, 6.2.3, 7.4.3), tantamount to a moral hazard justifying inadequate action. Disrupting that technology-legitimated narrative will thus remain the task of facing this moral hazard head-on. In this research, I have endeavoured to indicate that "middle-ground" organisations can contest sociotechnical transitions — and, in conclusion, it is critical that they continue to do so.


[^8.1]: Something that I was not able to follow through with Unite, due to intervening pandemic circumstances, leading rather to an expanded exploration of the post-green new deal prospects of the working-class environmentalism.
