`r if(knitr:::is_latex_output()) '\\startappendices'`

`r if(!knitr:::is_latex_output()) '# (APPENDIX) Appendix {-}'`

<!-- If you feel it necessary to include an appendix, it goes here. The first appendix should include the commands above. -->

# Appendix I: Foundational concepts

Throughout this thesis, I repeatedly refer to a few foundational concepts, some of which are also mentioned or implied in its title. They function as guiding notions for my research. While some are discussed in more detail in the thesis, others remain tacitly assumed, so here I are their definitions and what they specifically denote in this thesis.

**Technology** is a polysemic notion. The English word "technology" collapses the distinction between *technique* as a form of rationality that guides actions following a set of formal rules and *technologies* as a variety of functional objects such as tools, instruments, machines, built structures, and infrastructures, and as the attendant practical skills necessary to use them. Beyond material objects, technology can denote symbolic systems such as language, money, or law. Accordingly, theories of technology and technological development have drawn out different and frequently opposing aspects.

Most notably, Martin Heidegger understood technology (Ger. *Technik*) as a form of calculative thinking that posits and consequently discovers the world as a standing stock of resources ready for human extraction and use [@heidegger_question_1977], foreclosing other forms of epistemic and practical relating to the world. Such understanding dovetails with much of the 20th-century ecological criticism of instrumental reason and ontic subordination of nature. Karl Marx understood technology rather in the second sense, as a productive force of collective labour objectified and sedimented into technical objects, primarily machinery, that can be used to substitute labour and thus either free up time from work or increase exploitation of workers [@marx_economic_1857a]. The resulting technological base and its destructive social and ecological effects are a result of the capitalist drive to accumulation and not of rationalisation per se. Alternative, democratic and ecological rationalities can be pursued to create non-extractivist and non-exploitative technologies [@feenberg_questioning_1999]. Beyond utilitarian notions that conceive technologies as objects to be used by human subjects on non-human nature, a tradition following in Gilbert Simondon's footsteps has proposed to understand technologies as assemblages that constitute relations between humans and things as well as things and things. Not as fixed objects but as imperfect processes that iteratively transform and thus birth new practical and epistemic relations [@simondon_mode_2011]. Technologies are thus forms of co-constitution.

For the purposes of this thesis, technology will be taken in a narrower sense to denote *interlocking, formally organised material and symbolic systems that constitute and structure sociometabolic exchanges between human societies and non-human nature*. They do so by performing work — converting energy to metabolise matter. They require and they organise flows of matter and energy. Four aspects in the debates around technology will be of particular salience for my inquiry: technological development as a social process; technology's structuring role in the social metabolism; technology's attained planetary scale in terms of interlocking technological systems, extensive extraction, and indirect pollution [@haff_technology_2014]; and technology's capacity to reproduce power and domination by shifting work onto others — humans, animals, and ecosystems [@hornborg_global_2016].


**Capitalism** as a mode of production is structured by the separation of workers from the means of production. This separation forces the majority of the population in capitalist societies to work for a wage to be able to secure their subsistence, which they do by purchasing commodified goods and services in the market [@lebowitz_capital_2003]. Workers have to produce quantities of goods and services beyond the cost necessary to meet their needs in order to generate a surplus. The surplus value created by the workers is appropriated by the owners of the means of production for private consumption and, more importantly, for re-investment into a further accumulation of capital. Under the conditions of the market, a capitalist enterprise has to continuously invest in increasing productivity and expanding production. Innovations in productivity and products yield competitive advantage and greater profits, but as innovations generalise across the sector, other enterprises catch up and reduce the initial innovator's surplus-value [@postone_time_1995]. It is a process that, in the aggregate, results in a growing economic output, i.e., an ever-greater quantity of goods and services produced in a given period of time. However, capitalist enterprises have to sell more products than the workers, capitalists, and investors combined can buy from their *past* wages, profits, and interests. Thus, to prevent a crisis of aggregate demand, overproduction of goods and overaccumulation of capital, the money to generate that surplus has to be borrowed from the *future*, and the process of borrowing and investment into productive capital needs to continue growing in order to remain sustainable [@heinrich_introduction_2012, 173]. This growth, however, can only be maintained either through ever-greater geographic expansion or the ever-broader commodification of non-commodified spheres of life. Importantly, from an environmental perspective, for that cycle of compounding growth to become truly continuous and grow at ever-larger geographic and metabolic scales, the capitalist mode of production requires an ever-greater extraction and conversion of matter and energy as well.

**Social metabolism** (also **socioeconomic metabolism**, **socioecological metabolism**) extends the notion of metabolism, denoting a dynamic exchange and processing of nutrients and wastes between an organism and its environment, to describe a society's biophysical basis. A social metabolism is defined by the inflows of energy and matter from the environment and the outflows of heat and waste into the environment. The application of the biophysical notion of metabolism in social theory goes back to Marx, who used the notion of *Stoffwechsel* to distinguish a general notion of labour as a foundation of human reproduction from the labour as a value-producing activity specific to a mode of production. Thus in *Capital vol. 1* [@marx_capital_1867, 184; @burkett_metabolism_2006], he notes: "Labour-process ... is the necessary condition for effecting exchange of matter between man and Nature; it is the everlasting Nature-imposed condition of human existence, and therefore is independent of every social phase of that existence, or rather, is common to every such phase."

Labour and its product have a double character. While the value-producing, abstract labour under capitalism produces commodities whose value is determined in the process of exchange, the concrete labour produces useful products that have a concrete biophysical basis in the energy and matter that went into producing them. The implication is that the process of production is subject to nature's laws and limits, but the driver of that process is social in its character, defined by the fundamental features of a mode of production, such as the accumulation of capital. All economic processes are thus an entanglement between the social and the biophysical sphere of causation [@pauliuk_socioeconomic_2015]. Furthermore, whereas labour is the necessary condition of sociometabolic relations between society and nature, technology gives form and scale to that labour as a process.

Social metabolism as a concept would go on to have a rich history in the social sciences, anthropology, and geography [@fischer-kowalski_societys_1998c; @fischer-kowalski_societys_1998d], and has developed since the 1970s through the efforts of environmental economists into a number of quantitative methods of analysis of sociometabolic exchanges, most notably material flow accounting, the appropriation of the net primary production used in calculating ecological footprints, and life-cycle assessment for products, and processes [@eurostat_economy-wide_2001; @haberl_human_2014]. Related concepts include modes of subsistence [@sieferle_subterranean_2001] and sociometabolic regimes [@fischer-kowalski_socioecological_2007]. This thesis explores the interplay of transitions in technologies, modes of production and sociometabolic regimes.

**Planetary boundaries** represent a model developed by Johann Rockström, Will Steffen, and a team of prominent Earth system scientists to conceptualise the Anthropocene as a combined destabilisation of a number of Earth's interdependent subsystems alongside climate. Planetary boundaries are "the non-negotiable planetary preconditions that humanity needs to respect in order to avoid the risk of deleterious or even catastrophic environmental change at continental to global scales" [@rockstrom_planetary_2009, 2]. Rockström et al. have isolated nine subsystems whose limited variability over the last 10.000 years of the interglacial Holocene period has created conditions for human societies to develop and thrive. The destabilisation of these systems would put in danger that "safe operating space for humanity". The nine planetary boundaries include climate change, ocean acidification, biosphere integrity loss, land-use change, global phosphorus and nitrogen cycle, freshwater use, atmospheric aerosol loading, and stratospheric ozone depletion. According to the 2015 Planetary Boundaries report, biodiversity loss and the biochemical cycles of nitrogen and phosphorus have already been pushed beyond the boundaries of their Holocenic stability, climate change and land-use change are on course to breach their boundaries, whereas ocean acidification and freshwater use are approaching the risk zone [@steffen_planetary_2015].

**Environmentalism** is commonly framed in terms of the "post-materialist" value orientations of affluent, mostly western consumer societies that have the privilege to focus on the issues of quality of life and conservation of the environment, as opposed to the primarily materialist concerns of less affluent societies over securing livelihood [@inglehart_silent_2015]. This view of environmentalism conceives it rather as a privilege than a necessity, implying that those struggling to secure their livelihood are less motivated by concerns for their environment. Against this post-materialist view, Ramachandra Guha and Joan Martinez-Alier have advanced the concepts of the environmentalism of the poor [@martinez-alier_environmentalism_2003] and the varieties of environmentalism [@guha_varieties_1997; @huber_ecological_2019; @leonardi_bringing_2019]. They have argued that environmentalisms are primarily grounded in *ecological distributiveal conflicts*, an understanding that considers the social costs of degradation, mitigation, conservation, or adaptation of the environment as directly linked to livelihood concerns, but always also linked with ideational values that can equally be grounded in biocentric cosmologies or "post-materialist" world-views (or, rather, as I will argue in chapter 4, in ecological rationality). From their perspective, environmental sustainability is entwined with social, ecological and epistemic justice. This thesis investigates two such varieties of environmentalism, working-class environmentalism focusing on distributiveal conflicts structured through the sphere of capitalist production, and degrowth environmentalism pivoting around distributiveal conflicts in the ongoing transformation of the fossil-fuelled industrial-capitalist social metabolism.


# Appendix II: Ethics approval
\includepdf[pages=-]{inserted-PDFs/ethics-approval.pdf}

# Appendix III: Permission for article reuse
\includepdf[pages=-]{inserted-PDFs/permission-for-reuse.pdf}
\includepdf[pages=-]{inserted-PDFs/Domazet-letter.pdf}
